<template>
<div class="about-redesign">
<section class="about-hero"><div class="container"><div class="about-hero-copy"><span class="eyebrow-pill">ABOUT AIPITALS</span><h1>We build AI systems<br>that handle the work<br><span>between every patient interaction.</span></h1><p>Aipitals helps clinics and diagnostic centres automate patient communication, follow-ups, and workflows — so healthcare teams can focus on what truly matters.</p><div class="hero-actions"><RouterLink class="btn btn-primary rounded-pill" to="/contact">Book a Demo</RouterLink><RouterLink class="btn btn-outline-primary rounded-pill" to="/how-it-works"><i class="bi bi-play-circle"></i> See Aipitals in Action</RouterLink></div></div><div class="about-hero-art"><img src="/assets/doctor-hero.jpg" alt="Healthcare team using Aipitals"><span class="about-stat one"><b>+38%</b><small>Appointments Booked</small></span><span class="about-stat two"><b>2,48,000+</b><small>Patient interactions automated</small></span></div></div></section>
<section class="section about-mission"><div class="container"><div class="about-row"><div class="side-index">01<br><small>OUR PURPOSE</small></div><div><span class="eyebrow-pill">OUR PURPOSE</span><h2>Our mission is <span>simple.</span></h2><p>To reduce the operational burden on healthcare teams using intelligent automation.</p></div><div><h3>Our Mission</h3><p>Empower healthcare businesses with AI systems that automate repetitive tasks, improve patient experience, and drive growth.</p></div><div><h3>Our Vision</h3><p>A world where every healthcare team has the time, tools, and intelligence to deliver exceptional care.</p></div></div></div></section>
<section class="section soft"><div class="container"><div class="side-title"><span>02<br><small>OUR VALUES</small></span><div><span class="eyebrow-pill">OUR VALUES</span><h2>What we believe in.</h2></div></div><div class="value-grid-redesign"><div v-for="v in values" :key="v.t"><i :class="v.i"></i><h3>{{v.t}}</h3><p>{{v.p}}</p></div></div></div></section>
<section class="section"><div class="container"><div class="story-panel"><div class="side-index">03<br><small>OUR STORY</small></div><div><span class="eyebrow-pill">OUR STORY</span><h2>Why we started <span>Aipitals</span></h2><p>We saw clinics and diagnostic centres struggling with the same challenges every day—missed calls, no-shows, manual follow-ups, repetitive tasks, and disconnected systems.</p><p>We believed AI could handle the operational work that consumes time and resources, so healthcare teams can focus on patients, not paperwork.</p><blockquote>“We’re not here to replace people. We’re here to remove the repetitive work that stands between care and time.”</blockquote></div><img src="/assets/doctor-hero.jpg" alt="Aipitals team"/></div></div></section>
<section class="section impact-section"><div class="container"><div class="impact-bar"><span><b>500+</b>Healthcare Businesses</span><span><b>2M+</b>Patient Interactions Automated</span><span><b>25M+</b>Messages & Calls Handled</span><span><b>98%</b>Customer Satisfaction</span><span><b>24/7</b>Always-on AI Support</span></div></div></section>
<section class="section soft"><div class="container"><div class="section-heading center"><span class="eyebrow-pill">OUR TEAM</span><h2>The minds behind <span>Aipitals.</span></h2><p>Healthcare operators, product thinkers and technology builders working together to transform patient operations.</p></div><div class="team-grid-final"><div v-for="m in team" :key="m.n" class="team-card-final"><div class="team-avatar"><i class="bi bi-person"></i></div><h3>{{m.n}}</h3><small>{{m.r}}</small><p>{{m.p}}</p></div></div></div></section>
<section class="section"><div class="container"><div class="cta-hero about-final-cta"><div class="cta-copy"><span class="eyebrow-pill">LET'S BUILD THE FUTURE OF HEALTHCARE TOGETHER</span><h2>Let's automate your <span>patient operations.</span></h2><p>Book a demo and see how Aipitals can fit into your clinic or diagnostic centre.</p><RouterLink class="btn btn-primary rounded-pill" to="/contact">Book a Demo <i class="bi bi-arrow-right"></i></RouterLink></div></div></div></section>
<CTASection />
</div>
</template>
<script setup>
import CTASection from '../components/CTASection.vue'
const team=[{n:'Abhishek Ojha',r:'Founder & CEO',p:'Building practical AI systems for healthcare teams.'},{n:'Rishabh Singh',r:'CTO',p:'Designing reliable technology for patient operations.'},{n:'Ayushi Sharma',r:'Head of Product',p:'Turning real healthcare workflows into simple products.'},{n:'Karan Mehta',r:'Head of Growth',p:'Helping healthcare businesses discover better operations.'}]
const values=[{t:'Patient First',p:'Every solution we build starts and ends with better patient care.',i:'bi bi-people'},{t:'Trust & Security',p:'We follow the highest standards of data privacy, security and compliance.',i:'bi bi-shield-check'},{t:'Innovation',p:'We constantly explore, learn and build to solve real healthcare problems.',i:'bi bi-stars'},{t:'Collaboration',p:'We grow together with our customers, partners and communities.',i:'bi bi-people-fill'},{t:'Integrity',p:'We believe in transparency, honesty and doing what’s right—always.',i:'bi bi-heart'}]
</script>
