<template>
<section class="demo-page"><div class="container">
  <div class="demo-hero"><div><span class="eyebrow-pill">BOOK A DEMO</span><h1>See what Aipitals<br>can automate for<br><span>your centre.</span></h1><p>Tell us a little about your clinic or diagnostic centre.<br>We’ll show you the workflows that could be automated.</p></div><div class="demo-hero-art"><div class="mini-dashboard large"><b>Aipitals Dashboard</b><div class="dash-stats"><span><b>128</b>Appointments Booked</span><span><b>96</b>Follow-ups</span><span><b>320</b>Patient Engaged</span></div><div class="dash-list"><span><i class="bi bi-calendar-check"></i> New Appointment Booked</span><span><i class="bi bi-bell"></i> Reminder Sent</span><span><i class="bi bi-arrow-repeat"></i> Follow-up Completed</span></div></div><div class="phone-demo"><div class="mock-head"><span class="status-dot"></span><b>Aipitals AI</b><small>Online</small></div><div class="mock-chat"><div class="mock-bubble ai">How can I help you?</div><div class="mock-bubble patient">I want to book an appointment</div><div class="mock-bubble ai">Sure! Please choose a preferred date.</div></div></div></div></div>
  <div class="demo-layout">
    <form v-if="!submitted" @submit.prevent="submit" novalidate class="demo-form">
      <h2>1. Tell us about your centre</h2><div class="choice-grid"><label :class="{selected:form.type==='Clinic'}"><input type="radio" v-model="form.type" value="Clinic"><span>Clinic</span></label><label :class="{selected:form.type==='Diagnostic Centre'}"><input type="radio" v-model="form.type" value="Diagnostic Centre"><span>Diagnostic Centre</span></label></div>
      <h2>2. What are you interested in?</h2><p class="form-hint">You can select multiple</p><div class="interest-list"><label v-for="(p,i) in products" :key="p.slug" :class="{selected:form.interests.includes(p.name)}"><input type="checkbox" v-model="form.interests" :value="p.name"><span class="interest-icon" :class="'c'+i"><i :class="['bi',p.icon]"></i></span><span><b>{{p.name}}</b><small>{{interestCopy[i]}}</small></span></label></div>
      <h2>3. Your details</h2><div class="row g-3"><div class="col-md-6"><label class="field-label">Full Name *</label><input v-model.trim="form.name" placeholder="Enter your full name"><small v-if="errors.name" class="field-error">{{errors.name}}</small></div><div class="col-md-6"><label class="field-label">Centre / Clinic Name *</label><input v-model.trim="form.org" placeholder="Enter your clinic or centre name"><small v-if="errors.org" class="field-error">{{errors.org}}</small></div><div class="col-md-6"><label class="field-label">Email *</label><input v-model.trim="form.email" type="email" placeholder="youremail@domain.com"><small v-if="errors.email" class="field-error">{{errors.email}}</small></div><div class="col-md-6"><label class="field-label">Phone / WhatsApp *</label><input v-model.trim="form.phone" placeholder="Enter your number"><small v-if="errors.phone" class="field-error">{{errors.phone}}</small></div><div class="col-md-6"><label class="field-label">Location (City) *</label><input v-model.trim="form.location" placeholder="Enter your city"><small v-if="errors.location" class="field-error">{{errors.location}}</small></div><div class="col-md-6"><label class="field-label">How did you hear about us?</label><select v-model="form.source"><option value="">Select an option</option><option>Google</option><option>LinkedIn</option><option>Referral</option><option>Social Media</option><option>Other</option></select></div></div>
      <button class="btn btn-primary btn-lg rounded-3 w-100 mt-3" :disabled="loading"><i class="bi bi-calendar2"></i> {{loading?'Submitting…':'Book My Demo'}} <i v-if="!loading" class="bi bi-arrow-right"></i></button><p class="privacy-note">We respect your time and data. No spam, ever.</p>
    </form>
    <div v-else class="demo-form success-box"><i class="bi bi-check-circle-fill"></i><h2>Thanks — your demo request is in.</h2><p>Our team will review your details and get in touch with you.</p><RouterLink to="/" class="btn btn-outline-primary rounded-pill">Back to Home</RouterLink></div>
    <aside class="demo-side"><h2>What happens next?</h2><p>A quick look at our simple process.</p><div class="next-steps"><div v-for="(x,i) in nextSteps" :key="x.t"><span>0{{i+1}}</span><i :class="x.i"></i><div><b>{{x.t}}</b><p>{{x.p}}</p></div></div></div><div class="security-card"><i class="bi bi-shield-check"></i><div><h3>Built with Security & Compliance</h3><p>Aipitals is designed around secure healthcare workflows and responsible data practices.</p><div class="compliance"><span>HIPAA</span><span>SOC 2</span><span>GDPR</span></div></div></div></aside>
  </div>
  <div class="contact-strip"><div><i class="bi bi-envelope"></i><b>Prefer to email us?</b><span>hello@aipitals.com</span><small>We usually reply within a few hours.</small></div><div><i class="bi bi-telephone"></i><b>Talk to our team</b><span>+91 98765 43210</span><small>Mon – Fri, 10:00 AM – 6:00 PM IST</small></div><div><i class="bi bi-clock"></i><b>Response time</b><span>Within 15 minutes</span><small>During business hours</small></div></div>
</div></section>
</template>
<script setup>
import { reactive, ref } from 'vue'
import { products } from '../data/products'
const interestCopy=['24/7 AI front desk for calls, chats & bookings','Automated follow-ups, reminders & recall campaigns','End-to-end diagnostic workflow management','Automated test instructions & preparation','Collect feedback, reviews & improve experience']
const form=reactive({type:'Clinic',interests:[],name:'',org:'',email:'',phone:'',location:'',source:''})
const errors=reactive({}),loading=ref(false),submitted=ref(false)
const nextSteps=[{t:'We understand your workflow',p:'We’ll learn about your operations, patient volume and current challenges.',i:'bi bi-people'},{t:'We show you Aipitals in action',p:'See a personalized demo of the relevant Aipitals systems and workflows.',i:'bi bi-play-circle'},{t:'We recommend the right systems',p:'Get a tailored plan for your centre with expected impact and next steps.',i:'bi bi-check-circle'}]
function submit(){Object.keys(errors).forEach(k=>delete errors[k]);if(!form.name)errors.name='Required';if(!form.org)errors.org='Required';if(!/^\S+@\S+\.\S+$/.test(form.email))errors.email='Enter a valid email';if(!form.phone)errors.phone='Required';if(!form.location)errors.location='Required';if(Object.keys(errors).length)return;loading.value=true;setTimeout(()=>{loading.value=false;submitted.value=true},700)}
</script>
