<template>
<div class="how-redesign">
  <section class="how-hero container">
    <div><span class="eyebrow-pill">HOW IT WORKS</span><h1>From setup to automation.<br><span>In days, not months.</span></h1><p>Aipitals connects to your existing systems, learns your workflows and starts handling approved patient interactions while your team stays in control.</p><div class="hero-actions"><RouterLink class="btn btn-primary rounded-pill" to="/contact">Book a Demo <i class="bi bi-arrow-right"></i></RouterLink><RouterLink class="btn btn-outline-primary rounded-pill" to="/">See it in action <i class="bi bi-play-circle"></i></RouterLink></div></div>
    <div class="how-dashboard"><div class="dash-title">Aipitals AI Layer <span><i class="bi bi-circle-fill"></i> Live</span></div><div class="workflow-track"><div v-for="x in systems" :key="x.t"><span><i :class="x.i"></i></span><b>{{x.t}}</b><small>{{x.p}}</small></div></div><div class="dash-chart"><i class="bi bi-graph-up"></i> Automation performance <b>+34%</b></div></div>
  </section>
  <section class="long-section"><div class="container"><div class="how-process"><div v-for="(x,i) in steps" :key="x.t"><span>0{{i+1}}</span><i :class="x.i"></i><h3>{{x.t}}</h3><p>{{x.p}}</p></div></div></div></section>
  <section class="long-section soft-bg"><div class="container"><div class="long-heading"><span class="eyebrow-pill">BUILT FOR YOUR WORKFLOW</span><h2>Configure once. <span>Automate every day.</span></h2><p>Start small, scale safely and keep your team in control at every step.</p></div><div class="capability-grid"><div class="info-card" v-for="x in controls" :key="x.t"><i :class="x.i"></i><h3>{{x.t}}</h3><p>{{x.p}}</p></div></div></div></section>
  <section class="long-section"><div class="container"><div class="control-panel"><div class="control-copy"><span class="eyebrow-pill">HUMAN HANDOFF</span><h2>When it matters, <span>your team takes over.</span></h2><p>If a conversation needs human attention, Aipitals routes it to the right staff member. Your team can pause, review or stop workflows at any time.</p></div><div class="control-list"><span><i class="bi bi-check-circle-fill"></i>Complex requests</span><span><i class="bi bi-check-circle-fill"></i>Clinical / sensitive queries</span><span><i class="bi bi-check-circle-fill"></i>Unhappy patients</span><span><i class="bi bi-check-circle-fill"></i>Custom rules</span></div></div></div></section>
  <section class="long-section soft-bg"><div class="container"><div class="long-heading"><span class="eyebrow-pill">IMPROVE. LEARN. IMPROVE.</span><h2>See what your workflows are doing.</h2><p>Monitor performance, review conversations and improve workflows over time.</p></div><div class="product-impact"><div><h2>Ready to see Aipitals <span>in your workflow?</span></h2><p>Tell us how your team works and we’ll show you where Aipitals can fit.</p><RouterLink class="btn btn-primary rounded-pill" to="/contact">Book a Demo <i class="bi bi-arrow-right"></i></RouterLink></div><div class="impact-metrics"><div><b>1,248</b><small>Conversations handled</small></div><div><b>876</b><small>Automated actions</small></div><div><b>214</b><small>Human handoffs</small></div><div><b>156</b><small>Appointments booked</small></div></div></div></div></section>
</div>
</template>
<script setup>
const systems=[{t:'LIS / EHR',p:'Secure connection',i:'bi bi-database'},{t:'CRM / PMS',p:'Patient context',i:'bi bi-people'},{t:'Scheduling',p:'Availability',i:'bi bi-calendar-check'},{t:'Billing',p:'Operational data',i:'bi bi-receipt'},{t:'WhatsApp',p:'Patient channel',i:'bi bi-whatsapp'},{t:'Phone / SMS',p:'Communication',i:'bi bi-telephone'}]
const steps=[{t:'Connect your existing systems.',p:'Securely connect Aipitals with the systems you already use.',i:'bi bi-link-45deg'},{t:'Teach Aipitals how your organisation works.',p:'Configure workflows, rules, timings, approved responses and escalation rules.',i:'bi bi-sliders'},{t:'Go live with the workflows you choose.',p:'Start small, scale safely and keep every workflow within your rules.',i:'bi bi-play-circle'},{t:'Human handoff when it matters.',p:'Route complex or sensitive conversations to your team instantly.',i:'bi bi-person-check'},{t:'Review. Learn. Improve.',p:'Monitor performance and continuously improve your workflows.',i:'bi bi-graph-up-arrow'}]
const controls=[{t:'Approved Workflows',p:'AI works within the workflows you configure.',i:'bi bi-shield-check'},{t:'Human Escalation',p:'Conversations can be routed to staff when needed.',i:'bi bi-person-check'},{t:'Access Controls',p:'Give each role the right level of access.',i:'bi bi-lock'},{t:'Audit & Logs',p:'Review actions and conversation history.',i:'bi bi-journal-text'}]
</script>
