<template>
<div class="products-page-redesign">
<section class="product-page-hero"><div class="container"><div class="product-hero-copy"><span class="eyebrow-pill">✦ OUR AI PRODUCTS</span><h1>AI systems built<br>around the <span>patient journey.</span></h1><p>A complete suite of AI systems that automate patient communication, follow-ups and workflows — so your team can focus on care, not admin.</p><div class="hero-actions"><RouterLink class="btn btn-primary rounded-pill" to="/contact">Book a Demo <i class="bi bi-arrow-right"></i></RouterLink><RouterLink class="btn btn-outline-primary rounded-pill" to="/how-it-works">See Aipitals in Action <i class="bi bi-play-circle"></i></RouterLink></div></div><div class="ecosystem-flow"><div class="ecosystem-steps"><span v-for="(x,i) in ecosystem" :key="x.t"><i :class="x.i"></i><b>{{x.t}}</b><small>{{x.p}}</small><em v-if="i<4"><i class="bi bi-chevron-right"></i></em></span></div><div class="product-cards-row"><RouterLink v-for="(p,i) in products" :key="p.slug" :to="'/products/'+p.slug" class="ecosystem-card"><div class="product-card-head"><div class="mini-icon" :class="'c'+i"><i :class="['bi',p.icon]"></i></div><span>0{{i+1}}</span></div><h3>{{shortNames[i]}}</h3><p>{{cardCopy[i]}}</p><div class="tiny-checks"><span v-for="f in p.features.slice(0,4)" :key="f">✓ {{f}}</span></div><b class="learn">Learn more →</b></RouterLink></div><div class="ecosystem-foot"><span>✦ Happier Patients. Stronger Practice. Sustainable Growth.</span></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading center"><span class="eyebrow-pill">OUR AI SYSTEMS</span><h2>Five powerful AI systems.<br><span>One seamless experience.</span></h2><p>Each system is built to solve a critical part of your patient journey. Use them individually or connect multiple systems for end-to-end automation.</p></div><div class="five-system-grid"><div v-for="(p,i) in products" :key="p.slug" class="system-card"><div class="product-card-head"><div class="mini-icon" :class="'c'+i"><i :class="['bi',p.icon]"></i></div><span>0{{i+1}}</span></div><h3>{{shortNames[i]}}</h3><p>{{cardCopy[i]}}</p><div class="system-preview" :class="'preview-'+i"><template v-if="i===0"><span>Hi, I want to book an appointment</span><span>Sure! Please choose a date.</span><span>Tomorrow, 10:30 AM</span></template><template v-else-if="i===1"><span>Dr. Sharma · Follow-up due</span><span>Reminder sent ✓</span><span>Reschedule available</span></template><template v-else-if="i===2"><span>Booked ✓</span><span>Sample collected ✓</span><span>Report delivered ✓</span></template><template v-else-if="i===3"><span>Fasting required</span><span>Checklist confirmed ✓</span><span>Instructions shared</span></template><template v-else><span>How was your experience?</span><b class="stars">★★★★★</b><span>Leave a review on Google</span></template></div><div class="tiny-checks"><span v-for="f in p.features.slice(0,4)" :key="f">✓ {{f}}</span></div><RouterLink :to="'/products/'+p.slug" class="learn">Learn more →</RouterLink></div></div><div class="all-systems-bar"><span><i class="bi bi-people"></i> All systems. One connected ecosystem.</span><RouterLink to="/how-it-works">See how it works</RouterLink><RouterLink to="/contact">Book a Demo</RouterLink></div></div></section>
<section class="section soft"><div class="container"><div class="built-panel"><div><span class="eyebrow-pill">BUILT FOR EVERY HEALTHCARE TEAM</span><h2>Built around how your <span>healthcare business works.</span></h2><p>Whether you run a clinic or a diagnostic centre, Aipitals adapts to your workflows and helps your team focus on what matters most—patient care.</p></div><div class="audience-grid"><div><i class="bi bi-hospital"></i><h3>For Clinics</h3><p>Improve patient communication, increase appointments, and build lasting patient relationships.</p><RouterLink to="/solutions/clinics">Explore Solutions for Clinics →</RouterLink></div><div><i class="bi bi-beaker"></i><h3>For Diagnostic Centres</h3><p>Streamline bookings, test preparation, operations, and patient experience end-to-end.</p><RouterLink to="/solutions/diagnostic-centres">Explore Solutions for Diagnostic Centres →</RouterLink></div></div></div></div></section>
<section class="section"><div class="container"><div class="why-aipitals"><div><span class="eyebrow-pill">WHY AIPITALS</span><h2>Why healthcare teams<br><span>choose Aipitals.</span></h2><p>We combine AI technology with healthcare understanding to deliver systems that are reliable, secure, and results-focused.</p></div><div class="why-stats"><span><b>30%+</b>Increase in returning patients</span><span><b>40%+</b>Reduction in missed opportunities</span><span><b>2–4x</b>More appointments in the first month</span><span><b>4.8/5</b>Average patient experience score</span></div></div></div></section>
</div>
</template>
<script setup>
import {products} from '../data/products'
const ecosystem=[{t:'ENQUIRE',p:'Patient reaches out',i:'bi bi-chat-dots'},{t:'BOOK',p:'Appointment scheduled',i:'bi bi-calendar-check'},{t:'PREPARE',p:'Preparation made easy',i:'bi bi-clipboard-check'},{t:'VISIT',p:'Patient experience',i:'bi bi-person-check'},{t:'RETURN',p:'Happy patient comes back',i:'bi bi-heart'}]
const shortNames=['WhatsApp AI Receptionist','Patient Recall','Diagnostic Patient OS','Diagnostic Preparation','Patient Experience']
const cardCopy=['AI-powered patient enquiries & appointments.','Automated follow-ups, reminders and recall campaigns.','End-to-end diagnostic workflow management.','Send test instructions and preparation steps.','Improve patient satisfaction, collect feedback and grow.']
</script>
