<template>
  <div v-if="product" class="long-product" :style="{'--accent':accent}">
    <section class="long-product-hero">
      <div class="container">
        <div>
          <span class="eyebrow-pill">{{ product.kicker }}</span>
          <h1>{{ product.heroTitle }} <span class="accent">{{ product.heroAccent }}</span></h1>
          <p>{{ product.description }}</p>
          <div class="hero-actions">
            <RouterLink class="btn btn-primary rounded-pill px-4" to="/contact">Book a Demo <i class="bi bi-arrow-right"></i></RouterLink>
            <button class="btn btn-outline-primary rounded-pill px-4" @click="scrollToAction"><i class="bi bi-play-circle"></i> Watch Demo</button>
          </div>
          <div class="hero-trust-row"><span><i class="bi bi-check-circle"></i> {{product.trust[0]}}</span><span><i class="bi bi-shield-check"></i> {{product.trust[1]}}</span><span><i class="bi bi-lightning-charge"></i> {{product.trust[2]}}</span></div>
        </div>
        <div class="long-hero-art">
          <div class="mock-panel">
            <div class="mock-top"><b>{{ product.name }}</b><span><i class="bi bi-three-dots"></i></span></div>
            <div class="mock-grid"><div class="mock-stat" v-for="m in product.metrics" :key="m.l"><b>{{m.v}}</b><small>{{m.l}}</small></div></div>
            <div class="mock-list"><span v-for="x in product.mockItems" :key="x"><i class="bi bi-check-circle-fill" style="color:var(--accent)"></i> {{x}}</span></div>
          </div>
          <div class="mock-phone">
            <div class="phone-head"><i class="bi bi-stars"></i> Aipitals AI</div>
            <div class="bubble">{{product.phone[0]}}</div><div class="bubble user">{{product.phone[1]}}</div><div class="bubble">{{product.phone[2]}}</div>
          </div>
        </div>
      </div>
    </section>

    <section class="long-section" id="demo">
      <div class="container">
        <div class="control-panel">
          <div class="control-copy"><span class="eyebrow-pill">SEE IT IN ACTION</span><h2>See {{product.shortName}} <span>in action.</span></h2><p>{{product.demoCopy}}</p><div class="hero-actions"><RouterLink class="btn btn-primary rounded-pill" to="/contact">Book a Demo <i class="bi bi-arrow-right"></i></RouterLink></div></div>
          <div class="mock-panel"><div class="mock-top"><b>Aipitals {{product.shortName}}</b><span>Live workflow</span></div><div class="step-track mini-track"><div class="step" v-for="(s,i) in product.demoSteps" :key="s"><div class="step-icon"><i :class="product.demoIcons[i]"></i></div><b>{{s}}</b><small>{{i===product.demoSteps.length-1?'Completed':'Automated'}}</small></div></div></div>
        </div>
      </div>
    </section>

    <section class="long-section soft-bg">
      <div class="container">
        <div class="long-heading"><span class="eyebrow-pill">THE PROBLEM</span><h2>{{product.problemTitle}} <span>{{product.problemAccent}}</span></h2><p>{{product.problemCopy}}</p></div>
        <div class="problem-cards"><div class="info-card" v-for="x in product.problems" :key="x.t"><i :class="x.i"></i><h3>{{x.t}}</h3><p>{{x.p}}</p></div></div>
      </div>
    </section>

    <section class="long-section">
      <div class="container">
        <div class="long-heading"><span class="eyebrow-pill">HOW IT WORKS</span><h2>{{product.workflowTitle}} <span>{{product.workflowAccent}}</span></h2><p>{{product.workflowCopy}}</p></div>
        <div class="step-track"><div class="step" v-for="(s,i) in product.workflow" :key="s.t"><div class="step-icon"><i :class="s.i"></i></div><b>{{i+1}}. {{s.t}}</b><small>{{s.p}}</small></div></div>
      </div>
    </section>

    <section class="long-section soft-bg">
      <div class="container">
        <div class="long-heading"><span class="eyebrow-pill">WHAT IT HANDLES</span><h2>Everything your team needs <span>on autopilot.</span></h2></div>
        <div class="capability-grid"><div class="info-card" v-for="f in product.features" :key="f"><i class="bi bi-check-circle"></i><h3>{{f}}</h3><p>Configured to your approved workflow and communication rules.</p></div></div>
      </div>
    </section>

    <section class="long-section">
      <div class="container"><div class="control-panel"><div class="control-copy"><span class="eyebrow-pill">AI THAT WORKS WITHIN YOUR CONTROL</span><h2>AI when it makes sense. <span>Humans when they matter.</span></h2><p>Aipitals follows configured workflows and keeps your team in control. Complex, sensitive or unsupported requests can move to a human.</p></div><div class="control-list"><span v-for="x in controlPoints" :key="x"><i class="bi bi-check-circle-fill"></i>{{x}}</span></div></div></div>
    </section>

    <section class="long-section soft-bg">
      <div class="container"><div class="long-heading"><span class="eyebrow-pill">BUILT TO WORK WITH YOUR TOOLS</span><h2>Connect Aipitals with the tools <span>you already use.</span></h2></div><div class="integration-row"><span v-for="x in integrations" :key="x">{{x}}</span></div></div>
    </section>

    <section class="long-section">
      <div class="container"><div class="product-impact"><div><span class="eyebrow-pill">SEE THE DIFFERENCE</span><h2>{{product.impactTitle}} <span>{{product.impactAccent}}</span></h2><p>{{product.impactCopy}}</p><RouterLink class="btn btn-primary rounded-pill" to="/contact">Talk to an Expert <i class="bi bi-arrow-right"></i></RouterLink></div><div class="impact-metrics"><div v-for="m in product.impactMetrics" :key="m.l"><b>{{m.v}}</b><small>{{m.l}}</small></div></div></div></div>
    </section>
  </div>
  <NotFound v-else />
</template>
<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { products } from '../data/products'
import NotFound from './NotFound.vue'
const route=useRoute(); const product=computed(()=>products.find(p=>p.slug===route.params.slug)); const accent=computed(()=>product.value?.accent||'#176ff0')
const integrations=['Practice EHRs','Google Calendar','WhatsApp','Twilio','MSG91','Google Sheets','Zoho CRM','Zapier']
const controlPoints=['Approved workflows','Human in the loop','Privacy & security','No autonomous clinical decisions']
const defaults={
 'whatsapp-ai-receptionist':{kicker:'WHATSAPP AI RECEPTIONIST',heroTitle:'Your AI front desk on',heroAccent:'WhatsApp.',shortName:'AI Receptionist',accent:'#22a66f',trust:['Works 24/7','HIPAA Ready','No setup headache'],metrics:[{v:'1,248',l:'Enquiries handled'},{v:'842',l:'Appointments booked'},{v:'356',l:'After-hours messages'}],mockItems:['Appointment booked','Availability checked','Confirmation sent','Reminder scheduled'],phone:['Hi, I want to book an appointment.','Tomorrow, 11:30 AM','Your appointment is confirmed ✓'],demoCopy:'Watch how Aipitals AI Receptionist handles a real patient conversation from enquiry to appointment confirmation.',demoSteps:['Patient message','AI understands','Checks availability','Takes action','Human handoff'],demoIcons:['bi bi-chat-dots','bi bi-stars','bi bi-calendar-check','bi bi-check2-circle','bi bi-person-check'],problemTitle:'Your team is busy.',problemAccent:'Patients still reach out.',problemCopy:'Manual handling creates missed enquiries, long response times and unnecessary front-desk workload.',problems:[{t:'Missed enquiries',p:'Calls and messages go unanswered when staff are busy.',i:'bi bi-telephone'},{t:'High workload',p:'Teams spend hours answering repetitive questions.',i:'bi bi-clock'},{t:'Lost bookings',p:'Patients move on when they cannot get quick responses.',i:'bi bi-calendar-x'},{t:'Poor experience',p:'Slow replies and follow-ups create friction.',i:'bi bi-emoji-frown'}],workflowTitle:'From message to resolution.',workflowAccent:'Every step automated.',workflowCopy:'Aipitals AI understands the request, follows your rules and takes the right action.',workflow:[{t:'Patient Sends Message',p:'Patient reaches out on WhatsApp or another configured channel.',i:'bi bi-whatsapp'},{t:'AI Understands',p:'Understands intent and language.',i:'bi bi-stars'},{t:'Checks & Decides',p:'Checks availability and configured workflows.',i:'bi bi-calendar-check'},{t:'Takes Action',p:'Books, answers, reschedules or shares information.',i:'bi bi-check2-circle'},{t:'Human Handoff',p:'Complex or sensitive conversations go to staff.',i:'bi bi-person-check'}],impactTitle:'See what Aipitals AI Receptionist',impactAccent:'can do for your practice.',impactCopy:'Automate routine patient communication while your team stays focused on patient care.',impactMetrics:[{v:'1,248',l:'Enquiries handled'},{v:'842',l:'Appointments booked'},{v:'356',l:'After-hours messages'},{v:'+34%',l:'Appointment growth'}]},
 'patient-recall-agent':{kicker:'PATIENT RECALL',heroTitle:'Bring patients back.',heroAccent:'Build lasting relationships.',shortName:'Patient Recall',accent:'#7655ed',trust:['Multi-channel outreach','Smart segmentation','No setup headache'],metrics:[{v:'1,248',l:'Patients reached'},{v:'312',l:'Responses'},{v:'126',l:'Appointments'}],mockItems:['Recall campaign active','Personalized message sent','Patient responded','Appointment booked'],phone:['Your follow-up is due. Would you like to book?','Yes, tomorrow works.','Appointment booked ✓'],demoCopy:'Watch how Aipitals identifies inactive patients, sends personalized reminders and brings them back to your practice.',demoSteps:['Identify','Segment','Reach out','Engage','Return & repeat'],demoIcons:['bi bi-people','bi bi-bullseye','bi bi-chat-dots','bi bi-reply','bi bi-calendar-check'],problemTitle:'Patients forget.',problemAccent:'Opportunities are lost.',problemCopy:'Every missed follow-up is an opportunity lost for better care, retention and revenue.',problems:[{t:'Inactive patients',p:'Patients forget to follow up or visit regularly.',i:'bi bi-person-x'},{t:'No reminders',p:'Teams manually remember thousands of patients.',i:'bi bi-bell'},{t:'Low revisit rate',p:'Fewer repeat visits lead to lower treatment acceptance.',i:'bi bi-arrow-down-right'},{t:'Lost revenue',p:'Opportunities slip away when patients do not stay in touch.',i:'bi bi-graph-down'}],workflowTitle:'Automated recall.',workflowAccent:'Real results.',workflowCopy:'Aipitals handles outreach so your patients keep coming back.',workflow:[{t:'Identify',p:'Find patients who are due for a visit.',i:'bi bi-people'},{t:'Segment',p:'Group patients based on your rules and preferences.',i:'bi bi-bullseye'},{t:'Reach Out',p:'Send personalized messages across configured channels.',i:'bi bi-chat-dots'},{t:'Engage',p:'Patients respond or click to book an appointment.',i:'bi bi-reply'},{t:'Return',p:'Appointments get booked and repeat care grows.',i:'bi bi-calendar-check'}],impactTitle:'More reactivations.',impactAccent:'More appointments. More growth.',impactCopy:'Turn silent patients into lifelong patients with structured recall campaigns.',impactMetrics:[{v:'1,248',l:'Patients reached'},{v:'312',l:'Responses'},{v:'126',l:'Appointments booked'},{v:'₹3.6L',l:'Revenue influenced'}]},
 'diagnostic-patient-os':{kicker:'DIAGNOSTIC PATIENT OS',heroTitle:'Run your diagnostics.',heroAccent:'Smarter. Faster. Better.',shortName:'Diagnostic OS',accent:'#3187f4',trust:['End-to-end flow','Real-time visibility','Smart automation'],metrics:[{v:'128',l:'Tests booked'},{v:'96',l:'Samples collected'},{v:'78',l:'Reports delivered'}],mockItems:['Sample collected','Testing in progress','Report ready','Report delivered'],phone:['Is my report ready?','Your sample is in testing.','We’ll notify you when the report is ready.'],demoCopy:'See how diagnostic centres manage appointments, samples, reports and patient communication in one workflow.',demoSteps:['Book & schedule','Sample collection','Processing & testing','Reports & results','Follow-up & insights'],demoIcons:['bi bi-calendar-check','bi bi-droplet','bi bi-microscope','bi bi-file-earmark-text','bi bi-graph-up'],problemTitle:'Disconnected systems.',problemAccent:'Delayed reports. Frustrated patients.',problemCopy:'Manual processes and fragmented tools create bottlenecks across your operation.',problems:[{t:'Disconnected workflows',p:'Multiple tools and manual updates slow the journey.',i:'bi bi-diagram-2'},{t:'Delays everywhere',p:'Patients repeatedly ask for report status.',i:'bi bi-clock'},{t:'Poor patient visibility',p:'Patients cannot see what is happening next.',i:'bi bi-eye-slash'},{t:'Lost opportunities',p:'Follow-ups and repeat testing slip through.',i:'bi bi-graph-down'}],workflowTitle:'One system.',workflowAccent:'Every step of the journey.',workflowCopy:'Diagnostic OS connects the entire operation — seamlessly.',workflow:[{t:'Book',p:'Patients book tests and appointments.',i:'bi bi-calendar-check'},{t:'Collect',p:'Sample collection status stays visible.',i:'bi bi-droplet'},{t:'Process',p:'Testing status updates automatically.',i:'bi bi-microscope'},{t:'Report',p:'Reports are prepared and delivered.',i:'bi bi-file-earmark-text'},{t:'Recall',p:'Follow-up and repeat testing stays moving.',i:'bi bi-arrow-repeat'}],impactTitle:'Run a more efficient,',impactAccent:'profitable diagnostic centre.',impactCopy:'Reduce manual work, deliver reports faster and create a better patient experience.',impactMetrics:[{v:'1,248',l:'Tests managed'},{v:'1,102',l:'Samples collected'},{v:'968',l:'Reports delivered'},{v:'₹18.6L',l:'Revenue influenced'}]},
 'diagnostic-preparation-agent':{kicker:'DIAGNOSTIC PREPARATION',heroTitle:'The right preparation.',heroAccent:'Before the test.',shortName:'Diagnostic Preparation',accent:'#f2a33b',trust:['Approved protocols','Automated reminders','Human escalation'],metrics:[{v:'98%',l:'Prep completion'},{v:'320',l:'Instructions sent'},{v:'24/7',l:'Patient support'}],mockItems:['Fasting guidance shared','Checklist confirmed','Reminder sent','Question escalated'],phone:['What should I do before my test?','Please follow the approved fasting instructions.','Preparation checklist shared ✓'],demoCopy:'Give every patient clear, test-specific preparation guidance before they arrive.',demoSteps:['Test selected','Instructions sent','Reminder scheduled','Preparation confirmed','Escalate questions'],demoIcons:['bi bi-clipboard','bi bi-send','bi bi-bell','bi bi-check2-circle','bi bi-person-check'],problemTitle:'Preparation gets missed.',problemAccent:'Patients arrive unprepared.',problemCopy:'Inconsistent instructions and last-minute questions create delays and repeat work.',problems:[{t:'Missed instructions',p:'Patients do not always see or understand preparation steps.',i:'bi bi-file-earmark-x'},{t:'Last-minute questions',p:'Staff repeat the same instructions throughout the day.',i:'bi bi-question-circle'},{t:'Unprepared visits',p:'Incorrect preparation can delay or repeat tests.',i:'bi bi-calendar-x'},{t:'Inconsistent guidance',p:'Different staff may communicate information differently.',i:'bi bi-exclamation-triangle'}],workflowTitle:'Preparation,',workflowAccent:'automated and consistent.',workflowCopy:'Use only approved information and route unsupported questions to staff.',workflow:[{t:'Test selected',p:'Identify the booked test and configured protocol.',i:'bi bi-clipboard'},{t:'Instructions',p:'Share approved test-specific instructions.',i:'bi bi-file-earmark-text'},{t:'Reminders',p:'Send scheduled reminders before the visit.',i:'bi bi-bell'},{t:'Confirm',p:'Capture preparation confirmation where configured.',i:'bi bi-check2-circle'},{t:'Human handoff',p:'Escalate questions outside approved information.',i:'bi bi-person-check'}],impactTitle:'Consistent preparation.',impactAccent:'Fewer delays.',impactCopy:'Patients know what to do before they arrive, while staff stay in control.',impactMetrics:[{v:'98%',l:'Preparation completion'},{v:'320',l:'Instructions sent'},{v:'24/7',l:'Support availability'},{v:'0',l:'Unapproved clinical decisions'}]},
 'patient-experience-reviews':{kicker:'PATIENT EXPERIENCE',heroTitle:'Delight patients.',heroAccent:'Earn their trust. Every time.',shortName:'Patient Experience',accent:'#ed5275',trust:['Automated feedback','Reputation growth','Real-time insights'],metrics:[{v:'1,248',l:'Feedback received'},{v:'4.7',l:'Average rating'},{v:'92%',l:'Issues resolved'}],mockItems:['Feedback collected','Issue detected','Team alerted','Review request sent'],phone:['How was your experience?','Great — 5 stars!','Thank you. We’d love your review.'],demoCopy:'Collect feedback, resolve issues and grow your reputation with automated workflows.',demoSteps:['Request feedback','Collect responses','Analyze sentiment','Resolve & follow up','Publish & grow'],demoIcons:['bi bi-chat-square-text','bi bi-clipboard-check','bi bi-emoji-smile','bi bi-headset','bi bi-star'],problemTitle:'Patients have a voice.',problemAccent:'Are you listening?',problemCopy:'A poor experience can be shared instantly — and a missed signal can become a reputation risk.',problems:[{t:'Unhappy patients',p:'Issues go unnoticed until negative feedback appears.',i:'bi bi-emoji-frown'},{t:'Lost reviews',p:'Happy patients do not always leave reviews consistently.',i:'bi bi-star'},{t:'No visibility',p:'You do not know what patients think in real time.',i:'bi bi-eye-slash'},{t:'Stalled growth',p:'Poor reputation can hold back new patient acquisition.',i:'bi bi-graph-down'}],workflowTitle:'Better experience.',workflowAccent:'Built on automation.',workflowCopy:'Aipitals delivers every step so your team can focus on patient care.',workflow:[{t:'Request feedback',p:'Automatically send feedback requests after configured interactions.',i:'bi bi-chat-square-text'},{t:'Collect responses',p:'Patients rate and share feedback in seconds.',i:'bi bi-clipboard-check'},{t:'Analyze sentiment',p:'Identify sentiment and priorities.',i:'bi bi-emoji-smile'},{t:'Resolve & follow up',p:'Your team resolves issues quickly.',i:'bi bi-headset'},{t:'Publish & grow',p:'Happy patients can leave authentic reviews.',i:'bi bi-star'}],impactTitle:'Happier patients.',impactAccent:'Higher ratings. Stronger growth.',impactCopy:'Turn patient experience into a growth engine with feedback, recovery and review workflows.',impactMetrics:[{v:'1,248',l:'Feedback received'},{v:'4.7',l:'Average rating'},{v:'186',l:'New reviews'},{v:'92%',l:'Issues resolved'}]}
}
Object.entries(defaults).forEach(([slug,d])=>Object.assign(products.find(p=>p.slug===slug)||{},d))
function scrollToAction(){document.getElementById('demo')?.scrollIntoView({behavior:'smooth'})}
</script>
